CC=gcc
all:
	gcc -pthread -Wall -g -o server server.c 
	gcc -pthread -Wall -g -o client client.c  	
server:
	gcc -pthread -Wall -g -o server server.c 
deliver:
	gcc -pthread -Wall -g -o client client.c
clean:
	rm -f *.o server client 
