CC=gcc
all:
	gcc -Wall -g -o server server.c 
	gcc -Wall -g -o deliver deliver.c 	
server:
	gcc -Wall -g -o server server.c
deliver:
	gcc -Wall -g -o deliver deliver.c 
clean:
	rm -f *.o server deliver 
